[project]
name = "funcoin"
version = "1.0.55"
description = "funcoin"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "ccxt>=4.4.18", "farfundb>=1.2.3", "fundrive[oss]>=2.0.86", "fundrive-alipan>=1.2.9", "funserver>=1.0.38", "funshell>=1.0.19", "funtable>=1.0.46", "funfile>=1.0.39", "funsecret>=1.4.84", "orjson>=3.10.10", "pandas>=2.2.0",]
[[project.authors]]
name = "牛哥"
email = "niuliangtao@qq.com"

[[project.authors]]
name = "farfarfun"
email = "farfarfun@qq.com"

[[project.maintainers]]
name = "牛哥"
email = "niuliangtao@qq.com"

[[project.maintainers]]
name = "farfarfun"
email = "farfarfun@qq.com"

[project.scripts]
funcoin = "funcoin.server.run:funcoin"
funcoin-download = "funcoin.server.download:funcoin_download"

[project.urls]
Organization = "https://github.com/farfarfun"
Repository = "https://github.com/farfarfun/funcoin"
Releases = "https://github.com/farfarfun/funcoin/releases"

[dependency-groups]
dev = [ "funbuild>=1.6.66",]

[tool.setuptools]
license-files = []
